### ISSUE TITLE
Class instance encoder ignores type if class was derived from dict or list

### ISSUE THREAD

**Issue by hoechenberger** [mverleg/pyjson_tricks#30]
Currently, `encoders.class_instance_encode()` contains the following lines:

```python
	if isinstance(obj, list) or isinstance(obj, dict):
		return obj
```

However, this makes it impossible to successfully serialize any class instance that has inherited from either `list` or `dict`:
```python
import json_tricks

class Foo(dict):
    def __init__(self):
        self.x = 2

if  __name__ == '__main__':
    f = Foo()
    print(json_tricks.dumps(f))
```
Output:
```
{}
```
The attribute was entirely lost, and so was the class name.

**Comment by mverleg** [comment]
Thanks for the report!

I'm not entirely sure what the desired behaviour should be. When serializing e.g. a OrderedDict, I think the current serialization is fine. How to determine if something that extends a dict is not enough like a dict anymore?

**Comment by hoechenberger** [comment]
We could maybe check if the object has a `__dict__` attribute? `dict` and `list` objects have none…

**Comment by mverleg** [comment]
That might be a successful trick yeah, it'd work for the `OrderedDict` example. I'm not sure `dict` and `OrderedDict` and friends not having `__dict__` is an implementation detail which might change one day, or something 'reliable'...

A concern I had is that a special encoder would probably be needed to combine the list/dict encoding and the class encoding for something that's somewhat of an edge case.

**Update**: After some testing I realized that list and dict objects don't ever seem to reach the encoder. Perhaps they are like floats and ints, which are encoded without. This is usually great for performance but has been rather annoying before (issue #18).

So I'm afraid this has to be closed as **'can't be fixed'**. If your results are different if you have a workaround, feel free to reopen.

(On a purely personal note, in my experience, extending lists is only a good idea if the change is very minor, otherwise it gets hard for other people to read your code and understand it... But feel free to disregard that).

**Comment by hoechenberger** [comment]
So… Do you think writing a custom encoder for my class could help? I'm really at a loss how to best get this to work :(

**Comment by mverleg** [comment]
I don't think you can use dumps with a custom encoder, as it will never be called. What you could do is call an encoder (maybe class serializer one) before passing to dumps. That's not very convenient if you have a deeply nested data structure, but otherwise might be acceptable (and it may be the only way anyway).

Perhaps you could do some meta-class Voodoo to make your class not be recognized as a list by dumps, but that sounds really hacky if it works at all...

Maybe there exists a jaon library other than `json` which this is built on. You'd have to adapt quite some code from json-tricks and it night well have disadvantages (`json` is python default for a reason).

Lastly you could refactor so the class isn't a list or dict anymore. Don't know your use case and it's probably quite some work, but it mught be the best way to go.

**Comment by hoechenberger** [comment]
Thanks for your help, I will report back once (if) I find a solution.

**Comment by mverleg** [comment]
Not saying it's a good way, but maybe you can trick the `json` implementation using this https://stackoverflow.com/a/6803738
