### ISSUE TITLE
Dump numpy data with optional precision

### ISSUE THREAD

**Issue by MiaoDX** [mverleg/pyjson_tricks#50]
Hei,

Thanks for this great library, the ease of dumping numpy data is really impressive. I am wondering, could it be possible to add one more param to control the saving precision of numpy data? Since in most cases, one float of three decimal place is enough (0.123 is okay, 0.129999.. is not necessary).

Any ideas?

**Comment by mverleg** [comment]
Unfortunately we can't do anything about floats (or other primitives). Python automatically encodes primitives and they never reach the hook code, so nothing can be changed. That's actually such a common problem for json-tricks that a label has been made for it :-)

Perhaps #48 will be of interest, since it will store as binary and thus save space (8 bytes for full precision instead of 5 for low precision as in the example). It's far from finished though.

**Comment by mverleg** [comment]
This does seem to suggest there is a possibility... Perhaps it can be looked into https://stackoverflow.com/questions/1447287/format-floats-with-standard-json-module

**Comment by mverleg** [comment]
I don't see this being possible anytime soon as long as this uses the standard json library, so I'm going to close it.
